"""baseline

Revision ID: 0001
Revises:
Create Date: 2026-07-12 20:20:00.976200

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_package_id'), ['package_id'], unique=False)

    op.create_table('packages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_status'), ['status'], unique=False)

    op.create_table('decisions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_id', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('review_reasons_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_decisions_package_id'), ['package_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('package_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('has_text_layer', sa.Boolean(), nullable=False),
    sa.Column('scan_quality', sa.Float(), nullable=True),
    sa.Column('classification_reason', sa.Text(), nullable=True),
    sa.Column('manually_overridden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'path', name='uq_document_package_path')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_package_id'), ['package_id'], unique=False)

    op.create_table('policy_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('package_id', sa.String(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('citations_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('policy_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_policy_evidence_package_id'), ['package_id'], unique=False)

    op.create_table('extraction_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('schema_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extraction_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extraction_runs_document_id'), ['document_id'], unique=False)

    op.create_table('extracted_fields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extraction_run_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('grounded', sa.Boolean(), nullable=False),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('field_status', sa.String(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_extracted_fields_extraction_run_id'), ['extraction_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_extracted_fields_field_status'), ['field_status'], unique=False)

    op.create_table('review_actions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extraction_run_id', sa.String(), nullable=False),
    sa.Column('field_name', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('original_value_json', sa.Text(), nullable=True),
    sa.Column('corrected_value_json', sa.Text(), nullable=True),
    sa.Column('validation_before_json', sa.Text(), nullable=True),
    sa.Column('validation_after_json', sa.Text(), nullable=True),
    sa.Column('reviewer', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_actions_extraction_run_id'), ['extraction_run_id'], unique=False)

    op.create_table('validation_failures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('extraction_run_id', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('rule', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_run_id'], ['extraction_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('validation_failures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_validation_failures_extraction_run_id'), ['extraction_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_failures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_validation_failures_extraction_run_id'))

    op.drop_table('validation_failures')
    with op.batch_alter_table('review_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_actions_extraction_run_id'))

    op.drop_table('review_actions')
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_fields_field_status'))
        batch_op.drop_index(batch_op.f('ix_extracted_fields_extraction_run_id'))

    op.drop_table('extracted_fields')
    with op.batch_alter_table('extraction_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extraction_runs_document_id'))

    op.drop_table('extraction_runs')
    with op.batch_alter_table('policy_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_policy_evidence_package_id'))

    op.drop_table('policy_evidence')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_package_id'))

    op.drop_table('documents')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_decisions_package_id'))

    op.drop_table('decisions')
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_packages_status'))
        batch_op.drop_index(batch_op.f('ix_packages_created_at'))

    op.drop_table('packages')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_package_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
