"""extraction run attempt column

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-13 00:02:47.852753

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraction_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extraction_runs', schema=None) as batch_op:
        batch_op.drop_column('attempt')

    # ### end Alembic commands ###
