"""validation failure superseded column

Revision ID: 0003
Revises: 0002
Create Date: 2026-07-13 03:03:50.444807

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_failures', schema=None) as batch_op:
        batch_op.add_column(sa.Column('superseded', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('validation_failures', schema=None) as batch_op:
        batch_op.drop_column('superseded')

    # ### end Alembic commands ###
