"""extracted field parent field column

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-13 07:00:12.830300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_field', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_extracted_fields_parent_field'), ['parent_field'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracted_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_extracted_fields_parent_field'))
        batch_op.drop_column('parent_field')

    # ### end Alembic commands ###
