/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard Summary */
        get: operations["get_dashboard_summary_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Packages */
        get: operations["list_packages_packages_get"];
        put?: never;
        /** Upload documents and create a new claim package */
        post: operations["create_package_packages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{package_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Package */
        get: operations["get_package_packages__package_id__get"];
        put?: never;
        post?: never;
        /** Delete Package */
        delete: operations["delete_package_packages__package_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{package_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-run extraction and validation for an existing package */
        post: operations["process_package_packages__package_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{package_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Package Status */
        get: operations["get_package_status_packages__package_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{package_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Package Documents */
        get: operations["list_package_documents_packages__package_id__documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{package_id}/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Package Document */
        get: operations["get_package_document_packages__package_id__documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{package_id}/documents/{document_id}/reclassify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reclassify Document */
        post: operations["reclassify_document_packages__package_id__documents__document_id__reclassify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{package_id}/documents/{document_id}/pages/{page}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document Page Image */
        get: operations["get_document_page_image_packages__package_id__documents__document_id__pages__page__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{package_id}/fields/{field_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Field Evidence */
        get: operations["get_field_evidence_packages__package_id__fields__field_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reviews/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reviews Queue */
        get: operations["reviews_queue_reviews_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{package_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get extracted fields and validation failures for reviewer queue */
        get: operations["get_package_review_packages__package_id__review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{package_id}/fields/{field_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a reviewer's approval or correction for a single field */
        post: operations["submit_field_review_packages__package_id__fields__field_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{package_id}/validation/re-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rerun Package Validation */
        post: operations["rerun_package_validation_packages__package_id__validation_re_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{package_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit the final approve/deny decision for a package */
        post: operations["submit_package_decision_packages__package_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{package_id}/policy-evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Policy Evidence */
        get: operations["get_policy_evidence_packages__package_id__policy_evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{package_id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Audit Trail */
        get: operations["get_audit_trail_packages__package_id__audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/packages/{package_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export the full claim result: decision, fields, and policy evidence */
        get: operations["export_package_packages__package_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuditEventItem */
        AuditEventItem: {
            /** Actor */
            actor: string;
            /** Action */
            action: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Detail */
            detail: {
                [key: string]: unknown;
            } | null;
        };
        /** Body_create_package_packages_post */
        Body_create_package_packages_post: {
            /** Files */
            files: string[];
        };
        /** DashboardSummaryResponse */
        DashboardSummaryResponse: {
            /** Total Packages */
            total_packages: number;
            /** Processing */
            processing: number;
            /** Awaiting Review */
            awaiting_review: number;
            /** Approved */
            approved: number;
            /** Flagged */
            flagged: number;
            /** Escalated */
            escalated: number;
            /** Processing Errors */
            processing_errors: number;
            /** Straight Through Rate */
            straight_through_rate: number;
            /** Top Validation Failures */
            top_validation_failures: components["schemas"]["ValidationFailureCount"][];
        };
        /** DecisionRequest */
        DecisionRequest: {
            decision: components["schemas"]["DecisionType"];
            /**
             * Review Reasons
             * @default []
             */
            review_reasons: string[];
        };
        /** DecisionResponse */
        DecisionResponse: {
            /** Package Id */
            package_id: string;
            decision: components["schemas"]["DecisionType"];
        };
        /**
         * DecisionType
         * @enum {string}
         */
        DecisionType: "approved" | "flagged" | "escalated";
        /** DocumentReclassifyRequest */
        DocumentReclassifyRequest: {
            doc_type: components["schemas"]["DocumentType"];
            /**
             * Reviewer
             * @default reviewer
             */
            reviewer: string;
        };
        /** DocumentReclassifyResponse */
        DocumentReclassifyResponse: {
            /** Document Id */
            document_id: string;
            doc_type: components["schemas"]["DocumentType"];
            /** Classification Reason */
            classification_reason: string | null;
            /** Manually Overridden */
            manually_overridden: boolean;
        };
        /** DocumentSummary */
        DocumentSummary: {
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            doc_type: components["schemas"]["DocumentType"];
            /** Has Text Layer */
            has_text_layer: boolean;
            /** Scan Quality */
            scan_quality: number | null;
            /** Classification Reason */
            classification_reason: string | null;
            /** Manually Overridden */
            manually_overridden: boolean;
        };
        /**
         * DocumentType
         * @description Every value the classifier can persist and return through the API.
         *
         *     This includes deep-extraction domains and classification-only supporting
         *     document types. Keep it in sync with both `doc_type=` and
         *     `supporting_types=` registrations in `src/claimflow/domains/*.py`.
         * @enum {string}
         */
        DocumentType: "cms1500" | "eob" | "medicare_summary_notice" | "xactimate" | "declarations_page" | "loan" | "sba_form_413" | "sba_form_2202" | "medical_bill" | "insurance_policy" | "denial_letter" | "clinical_note" | "lab_report" | "discharge_summary" | "referral_letter" | "prior_authorization_letter" | "eligibility_benefits_verification" | "ub04_cms1450" | "loss_report" | "contractor_invoice" | "adjuster_notes" | "roof_inspection_report" | "damage_photo" | "material_receipt" | "fire_report" | "police_report" | "tax_return" | "bank_statement" | "balance_sheet" | "income_statement" | "id_document" | "supporting_exhibit" | "profit_loss_statement" | "debt_schedule" | "business_license" | "articles_of_incorporation" | "payroll_report" | "w2_1099_paystub" | "unknown";
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: unknown;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        /** ExportResponse */
        ExportResponse: {
            /** Package Id */
            package_id: string;
            status: components["schemas"]["PackageStatus"];
            decision: components["schemas"]["DecisionType"] | null;
            /** Domain */
            domain: string | null;
            /** Extraction Fields */
            extraction_fields: components["schemas"]["ExtractionFieldExport"][];
            /** Validation Failures */
            validation_failures: components["schemas"]["ValidationFailureItem"][];
            /** Policy Answers */
            policy_answers: components["schemas"]["PolicyAnswerExport"][];
        };
        /** ExtractionFieldExport */
        ExtractionFieldExport: {
            /** Name */
            name: string;
            /** Value */
            value: unknown | null;
            /** Final Value */
            final_value: unknown | null;
            /** Confidence */
            confidence: number;
            /** Grounded */
            grounded: boolean;
            /** Valid */
            valid: boolean;
            /** Field Status */
            field_status: string;
            /** Parent Field */
            parent_field?: string | null;
            /** Reviewer Action */
            reviewer_action?: string | null;
            /** Reviewer */
            reviewer?: string | null;
            /** Reviewer Note */
            reviewer_note?: string | null;
        };
        /** FieldEvidenceResponse */
        FieldEvidenceResponse: {
            /** Field Id */
            field_id: number;
            /** Name */
            name: string;
            /** Value */
            value: unknown | null;
            /** Confidence */
            confidence: number;
            /** Document Id */
            document_id: string;
            /** Filename */
            filename: string;
            /** Page */
            page: number | null;
            /** Quote */
            quote: string | null;
            /** Bbox */
            bbox: number[] | null;
            /**
             * Coordinate System
             * @default pdf_points
             */
            coordinate_system: string;
            /** Block Type */
            block_type: string | null;
            /** Evidence Unavailable */
            evidence_unavailable: boolean;
        };
        /** FieldReviewRequest */
        FieldReviewRequest: {
            action: components["schemas"]["ReviewActionType"];
            /** Corrected Value */
            corrected_value?: unknown | null;
            /** Validation After */
            validation_after?: string[] | null;
            /**
             * Reviewer
             * @default reviewer
             */
            reviewer: string;
            /** Note */
            note?: string | null;
        };
        /** FieldReviewResponse */
        FieldReviewResponse: {
            /** Field Id */
            field_id: number;
            action: components["schemas"]["ReviewActionType"];
            /** Reviewer */
            reviewer: string;
            /** Corrected Value */
            corrected_value: unknown | null;
        };
        /** PackageCreateResponse */
        PackageCreateResponse: {
            /** Package Id */
            package_id: string;
            status: components["schemas"]["PackageStatus"];
        };
        /** PackageDeleteResponse */
        PackageDeleteResponse: {
            /** Package Id */
            package_id: string;
            /** Status */
            status: string;
        };
        /** PackageDetailResponse */
        PackageDetailResponse: {
            /** Package Id */
            package_id: string;
            status: components["schemas"]["PackageStatus"];
            /** Result */
            result: {
                [key: string]: unknown;
            } | null;
            /** Error */
            error: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Domain */
            domain?: string | null;
            /** Decision */
            decision?: string | null;
            /**
             * Review Reasons
             * @default []
             */
            review_reasons: string[];
            /** Overall Confidence */
            overall_confidence?: number | null;
            /**
             * Document Count
             * @default 0
             */
            document_count: number;
            /**
             * Validation Failure Count
             * @default 0
             */
            validation_failure_count: number;
        };
        /** PackageReviewResponse */
        PackageReviewResponse: {
            /** Package Id */
            package_id: string;
            status: components["schemas"]["PackageStatus"];
            /** Fields */
            fields: components["schemas"]["ReviewFieldSummary"][];
            /** Validation Failures */
            validation_failures: components["schemas"]["ReviewValidationFailure"][];
        };
        /**
         * PackageStatus
         * @enum {string}
         */
        PackageStatus: "uploaded" | "queued" | "processing" | "review_ready" | "completed" | "processing_error" | "validation_error" | "retrieval_error";
        /** PackageStatusResponse */
        PackageStatusResponse: {
            /** Package Id */
            package_id: string;
            status: components["schemas"]["PackageStatus"];
        };
        /** PackageSummary */
        PackageSummary: {
            /** Package Id */
            package_id: string;
            status: components["schemas"]["PackageStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Domain */
            domain?: string | null;
            /** Decision */
            decision?: string | null;
            /** Overall Confidence */
            overall_confidence?: number | null;
            /** Document Count */
            document_count: number;
            /** Validation Failure Count */
            validation_failure_count: number;
        };
        /** PaginatedPackagesResponse */
        PaginatedPackagesResponse: {
            /** Items */
            items: components["schemas"]["PackageSummary"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** PolicyAnswerExport */
        PolicyAnswerExport: {
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Citations */
            citations: unknown[];
        };
        /** PolicyEvidenceItem */
        PolicyEvidenceItem: {
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Citations */
            citations: unknown[];
        };
        /**
         * ReviewActionType
         * @enum {string}
         */
        ReviewActionType: "approve" | "edit" | "reject" | "add";
        /** ReviewFieldSummary */
        ReviewFieldSummary: {
            /** Field Id */
            field_id: number;
            /** Name */
            name: string;
            /** Value */
            value: unknown | null;
            /** Confidence */
            confidence: number;
            /** Field Status */
            field_status: string;
            /** Parent Field */
            parent_field: string | null;
            /** Reviewer Action */
            reviewer_action?: string | null;
            /** Corrected Value */
            corrected_value?: unknown | null;
            /** Reviewer */
            reviewer?: string | null;
            /** Reviewer Note */
            reviewer_note?: string | null;
        };
        /** ReviewValidationFailure */
        ReviewValidationFailure: {
            /** Field */
            field: string;
            /** Rule */
            rule: string;
            /** Reason */
            reason: string;
        };
        /** SettingsResponse */
        SettingsResponse: {
            /** Confidence Threshold */
            confidence_threshold: number;
            /** Escalation Threshold */
            escalation_threshold: number;
            /** Enabled Domains */
            enabled_domains: string[];
            /** Doc Intel Provider */
            doc_intel_provider: string;
            /** Doc Intel Model */
            doc_intel_model: string;
            /** Ocr Provider */
            ocr_provider: string;
            /** Ocr Fallback Providers */
            ocr_fallback_providers: string[];
            /** Qdrant Url */
            qdrant_url: string;
            /** Qdrant Collection */
            qdrant_collection: string;
            /** Langfuse Enabled */
            langfuse_enabled: boolean;
            /** Anthropic Api Key Configured */
            anthropic_api_key_configured: boolean;
        };
        /** ValidationFailureCount */
        ValidationFailureCount: {
            /** Rule */
            rule: string;
            /** Count */
            count: number;
        };
        /** ValidationFailureItem */
        ValidationFailureItem: {
            /** Field */
            field: string;
            /** Rule */
            rule: string;
            /** Reason */
            reason: string;
        };
        /** ValidationRerunRequest */
        ValidationRerunRequest: {
            /**
             * Corrected Fields
             * @default {}
             */
            corrected_fields: {
                [key: string]: unknown;
            };
        };
        /** ValidationRerunResponse */
        ValidationRerunResponse: {
            /** Validation Failures */
            validation_failures: components["schemas"]["ValidationFailureItem"][];
            decision: components["schemas"]["DecisionType"];
            /** Decision Changed */
            decision_changed: boolean;
            previous_decision: components["schemas"]["DecisionType"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_dashboard_summary_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummaryResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_settings_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_packages_packages_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                status?: string | null;
                domain?: string | null;
                decision?: string | null;
                confidence_min?: number | null;
                confidence_max?: number | null;
                validation_rule?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                search?: string | null;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPackagesResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_package_packages_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_package_packages_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageCreateResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_package_packages__package_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    delete_package_packages__package_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageDeleteResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    process_package_packages__package_id__process_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageCreateResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_package_status_packages__package_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageStatusResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_package_documents_packages__package_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSummary"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_package_document_packages__package_id__documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSummary"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    reclassify_document_packages__package_id__documents__document_id__reclassify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentReclassifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentReclassifyResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_document_page_image_packages__package_id__documents__document_id__pages__page__get: {
        parameters: {
            query?: {
                bbox?: string | null;
            };
            header?: never;
            path: {
                package_id: string;
                document_id: string;
                page: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_field_evidence_packages__package_id__fields__field_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
                field_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldEvidenceResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    reviews_queue_reviews_queue_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                status?: string | null;
                domain?: string | null;
                decision?: string | null;
                confidence_min?: number | null;
                confidence_max?: number | null;
                validation_rule?: string | null;
                date_from?: string | null;
                date_to?: string | null;
                search?: string | null;
                sort?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPackagesResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_package_review_packages__package_id__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageReviewResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    submit_field_review_packages__package_id__fields__field_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
                field_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FieldReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FieldReviewResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    rerun_package_validation_packages__package_id__validation_re_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidationRerunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationRerunResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    submit_package_decision_packages__package_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecisionResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_policy_evidence_packages__package_id__policy_evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyEvidenceItem"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_audit_trail_packages__package_id__audit_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventItem"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    export_package_packages__package_id__export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
